import { ExecutionLog } from "@prisma/client";

import { 
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { LogLevel } from "@/features/log/types";

interface LogViewerProps {
  logs: ExecutionLog[] | undefined;
}

export const LogViewer = ({ logs }: LogViewerProps) => {
  if (!logs || logs.length === 0) return null;

  return (
    <Card className="w-full">
      <CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
        <CardTitle className="text-base">Logs</CardTitle>
        <CardDescription className="text-muted-foreground text-sm">
          Logs generated by this phase
        </CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader className="text-muted-foreground text-sm">
            <TableRow>
              <TableHead>Time</TableHead>
              <TableHead>Level</TableHead>
              <TableHead>Message</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {logs.map((log) => (
              <TableRow key={log.id} className="text-muted-foreground">
                <TableCell width={190} className="text-xs text-muted-foreground">
                  {log.timestamp.toISOString()}
                </TableCell>
                <TableCell width={80} className={cn(
                  "uppercase text-xs font-bold p-[3px] pl-4",
                  (log.logLevel as LogLevel) === "error" && "text-destructive",
                  (log.logLevel as LogLevel) === "info" && "text-primary",
                )}>
                  {log.logLevel}
                </TableCell>
                <TableCell>{log.message}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}